#! /bin/sh
#
# Script used by the Zenoss Dev team (the authors of pynetsnmp) to
# release and deploy updated versions.  First, go edit setup.py
# and update the VERSION value.
#
# Run this script.  This will generate a tarball in the parent
# directory (..).  Move this script to your zenoss inst/externallibs
# directory and remove the old tarball and add the new one:
#
# $ svn remove pynetsnmp-OLDVERSION.tar.gz
# $ svn add pynetsnmp-NEWVERSION.tar.gz
#
# Then you are set to re-release Zenoss.
#

quit() {
   echo $@
   exit 1  
}
PACKAGE=pynetsnmp
VERSION=`python -c 'import version; print version.VERSION'`
VPACKAGE=$PACKAGE-$VERSION
SVN=http://dev.zenoss.org/svnint
SVNTRUNK=$SVN/trunk/core/$PACKAGE
SVNTAG=$SVN/tags/core/$VPACKAGE
svn cp -m"making release $VERSION" $SVNTRUNK $SVNTAG || quit cannot create tag
svn export $SVNTAG /tmp/$VPACKAGE || quit cannot create export tree
OLD=`pwd`
( 
  cd /tmp
  tar -czvf $OLD/../$VPACKAGE.tar.gz $VPACKAGE
  rm -rf $VPACKAGE
) || quit cannot create tarball
echo "Remember to move ../$VPACKAGE.tar.gz the Zenoss "
echo "inst/externallibs directory and check it in."
exit 0
