class SnmpTimeoutError(Exception): ...
class ArgumentParseError(Exception): ...
class TransportError(Exception): ...

class SnmpError(Exception):
    def __init__(self, message, *args, **kwargs): ...

class SnmpNameError(SnmpError):
    def __init__(self, oid): ...

class SnmpUsmError(SnmpError): ...
class SnmpUsmStatsError(SnmpUsmError): ...
